apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slipchuk-python-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/SergSL2022/step-project-final.git'
    targetRevision: HEAD
    path: charts/slipchuk-python-app
    helm:
      valueFiles:
        - ../../argocd/python-api.values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: python-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
