name: Build and Deploy

on:
  push:
    paths:
      - 'python/**'
    branches:
      - main
  pull_request:
    paths:
      - 'python/**'
    branches:
      - main

env:
  REGISTRY_USER: ${{ secrets.DOCKERHUB_USER_NAME }}
  REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME: serhiyslipchuk/slipchuk-python-app
  TAG: v.0.${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
