---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slipchuk-docker-registry-secret
  namespace: python-api
spec:
  encryptedData:
    .dockerconfigjson: AgBRooIqm9l6COAq9ekQ5bOPA6G39lAb2QhloyPr2aikhVRY5aaZRddQk59EGikQOOotMz92XfTnF9F9mzkR+kNEhJZJKrVlIjmr01QC4Sa02jpv+dHejCdzLghVZML6fHUHMpBbTPoCSdfLQ5oubfr8kZiDavdvueVYC6yMBpchb3YD79z4Py3KOPKjtZWFkmHa35ad1iZhU7hKuj1CrwwwAg75MylMHPZcX8No1wUI3i2o8b2E9//3AsnF6ADWkdNnKdYjDqRZZmRuVJStcCGQ5KTfbKZ6vR7fKkFJ59MMeqBYSyftx6T3HzBxQtKApPn14AyB2+gTuNoXmECdni6p1FUcCnKF1hH/M9Q4nDEi8Rwu7/15RzUikVhb2e6/WZksUpgUP7ZspGJwLelXI4ol/yQhlonsrTc/xLOD6iaj0ag5lKz6ZB8WhsFACZJARdAOuLBbj7k87Pr0rXn6xQZhBmeuzp8ZaR/9yyWIN++hC4o3Q1Hqdq7GJ/WodqVjp4azhnxM13tcNTIW2h1iRZY0MBrBLDANphi3xFH6G6ZzLPC5sDbU85tXh/60cT1zEDh6JSaiiPYLWMmbQICqeiTXbHDxDHo2Xt79Cnxo3sapcwyfD9L+AXKbgkysSTZDhPdKIz/OWjIixgoSQe3OahCqelRIdnvsQZSv81Z141FASHHXMId21iW3K7y3AYNLep18do3+JfqwL6sRHxzjudlPcDFrfqCaFHQ7KYVsKf8WFOn+02k/qnfLNbvzSyIGCm1LOjWCfB72JjghbRDYMbOzI8RqDdHoucEN68iXvQpP2C1Zc/FeUM4h0jjOxlnlh8jNzhX3Cdzkh4OJlcVbWhPoB1mg3vvCbxOLFLVDHfAFrBGSq8IhhpJrUM/LZyQH6dvphKsLLRgMI9IcfkU/byLu9It1uiauJNLJJ8FCyv1WxOlMufRIYv8YKe7GHQ==
  template:
    metadata:
      creationTimestamp: null
      name: slipchuk-docker-registry-secret
      namespace: python-api
